services:
  app:
    build:
      context: ..
      dockerfile: /Dockerfile
    volumes:
      - ../build:/usr/share/nginx/html
    ports:
      - ${APP_PORT:-4000}:80
    networks:
      - app_network
    restart: no


networks:
  app_network:
